<?php
$preblocks = array (
  'id' => 1,
  'moduleID' => 1,
  'createdBy' => 1,
  'created' => 1,
  'updatedBy' => 1,
  'updated' => 1,
  'origId' => 1,
  'sortnr' => 1,
  'showBrandLine' => 1,
  'showContactList' => 1,
  'logo' => 1,
  'headerBackground' => 1,
  'content_status' => 1,
  'show_brand_logo' => 1,
  'brand_logo' => 1,
  'activate_channel_admin' => 1,
  'groupId' => 1,
  'activateHelpButton' => 1,
  'activateReadIntroNewUsers' => 1,
  'user_session_reload_interval_minutes' => 1,
  'activate_module_hiding_script' => 1,
  'activate_url_sharing' => 1,
  'activate_account_settings' => 1,
  'account_settings_modulename' => 1,
  'custom_terms_tablename' => 1,
);
?>