<?php
$formText_PhoneNumber_output="";
$formText_DateFrom_output="";
$formText_DateTill_output="";
$formText_Customer_output="";
$formText_ContactPerson_output="";
$formText_Active_outputKeycard="";
$formText_Showing_Output="";
$formText_Of_output="";
$formText_ShowMore_output="";
$formText_BackToCustomer_Output="";
$formText_ActiveGateAccesses_output="";
$formText_All_output="";
$formText_PhoneNumber_output_gate="";
$formText_Customer_output_gate="";
$formText_ContactPerson_output_gate="";
$formText_Search_output="";
?>