<?php
$preblocks = array (
  'id' => 1,
  'moduleID' => 1,
  'createdBy' => 1,
  'created' => 1,
  'updatedBy' => 1,
  'updated' => 1,
  'origId' => 1,
  'sortnr' => 1,
  'content_status' => 1,
  'name' => 1,
  0 => 
  array (
    'sys_name' => $formText_InvoiceConfig_settingBlocks,
    'sys_childs' => 
    array (
      'companyname' => 1,
      'companypostalbox' => 1,
      'companyzipcode' => 1,
      'companypostalplace' => 1,
      'companyCountry' => 1,
      'companyphone' => 1,
      'companyEmail' => 1,
      'companyorgnr' => 1,
      'kidOnInvoice' => 1,
      'kidCustNumAmount' => 1,
      'kidPaymentType' => 1,
      'kidInvNumAmount' => 1,
      'kidOwnercompanyId' => 1,
      'invoiceFromEmail' => 1,
      'invoiceSubjectEmail' => 1,
      'invoiceTextEmail' => 1,
      'invoicelogo' => 1,
      'invoicelogoWidth' => 1,
      'invoicelogoPositionX' => 1,
      'invoicelogoPositionY' => 1,
      'invoicebottomtext' => 1,
      'companyaccount' => 1,
      'companyiban' => 1,
      'companyswift' => 1,
      'companyBankAccount2' => 1,
      'companyiban2' => 1,
      'companyswift2' => 1,
      'companyBankAccount3' => 1,
      'companyiban3' => 1,
      'companyswift3' => 1,
      'emailFromExtra1' => 1,
      'EmailFromExtra2' => 1,
      'EmailFromExtra3' => 1,
      'numberDecimalsOnInvoice' => 1,
      'accountRoundingsOnInvoice' => 1,
      'allowMultiCurrencies' => 1,
      'currencyNameWhenOnlyOne' => 1,
      'currencyCodeWhenOnlyOne' => 1,
      'nextInvoiceNr' => 1,
      'set_next_invoicenumber_automatic' => 1,
    ),
    'sys_collapse' => '0',
  ),
  1 => 
  array (
    'sys_name' => $formText_CustomerId_settingBlocks,
    'sys_childs' => 
    array (
      'customerid_autoormanually' => 1,
      'nextCustomerId' => 1,
      'use_integration' => 1,
    ),
    'sys_collapse' => '0',
  ),
  'exportScriptFolder' => 1,
  'accountCustomerLedger' => 1,
  'avtalegiro_data_sender' => 1,
  'avtalegiro_drawing_reference_text' => 1,
  'external_company_id' => 1,
  'accountingproject_id' => 1,
  'external_ownercompany_code' => 1,
  'accountingproject_code' => 1,
  'clientNumberFactoring' => 1,
  'activatePeriodization' => 1,
  'balancePeriodizationAccountcode' => 1,
  'exportSendMethod' => 1,
  'exportFtpUsername' => 1,
  'exportFtpPassword' => 1,
  'exportFtpHost' => 1,
  'exportFtpPort' => 1,
  'exportFtpPath' => 1,
  'exportFtpUseSSL' => 1,
  'export2SendMethod' => 1,
  'export2FtpUsername' => 1,
  'export2FtpPassword' => 1,
  'export2FtpHost' => 1,
  'export2FtpPort' => 1,
  'export2FtpPath' => 1,
  'export2FtpUseSSL' => 1,
  'export2ScriptFolder' => 1,
  'accountingdepartment_code' => 1,
  'extra_text_after_company_org_number' => 1,
  'identity_id' => 1,
);
?>