<?php
$formText_Offers_output="";
$formText_January_output="";
$formText_February_output="";
$formText_March_output="";
$formText_April_output="";
$formText_May_output="";
$formText_June_output="";
$formText_July_output="";
$formText_August_output="";
$formText_September_output="";
$formText_October_output="";
$formText_November_output="";
$formText_December_output="";
$formText_LatestReadByCustomer_output="";
$formText_Date_output="";
$formText_Time_output="";
$formText_Customer_output="";
$formText_Offer_output="";
$formText_LatestSentToCustomer_output="";
?>