<?php
$formText_ErrorUpdatingDatabaseForPlan_output="";
$formText_ErrorUpdatingDatabaseForPlanline_output="";
$formText_FollowingSubscriptionsAreEndingSoon_AutoTask="";
$formText_Customer_AutoTask="";
$formText_SubscriptionName_AutoTask="";
$formText_StartDate_AutoTask="";
$formText_StopDate_AutoTask="";
$formText_AutoTaskCannotBeFound_Output="";
?>