<?php
$formText_MissingFilesToAttachToInvoice="";
$formText_InvoiceMissingExternalInvoiceNr="";
$formText_IntegrationSyncingFailed="";
$formText_InvoiceMissingKidNumber="";
$formText_ErrorCreatingPdf="";
$formText_MissingEhfConfigurationForVat_Output="";
$formText_EhfInvoiceFileValidationFailed_Output="";
$formText_MoreInfo_Output="";
$formText_NotDelivered_Output="";
$formText_InvoiceNumber_Output="";
$formText_InvalidEmailSpecified_Output="";
$formText_InvoiceHasNotBeSentByEmailToCustomer_Output="";
$formText_of_Output="";
$formText_EmailAddressesIsInvalidForCustomer_Output="";
$formText_InvoicesForPrint_output="";
$formText_Hi_output="";
$formText_YouCanDownloadInvoicesForPrintFromBatchinvoicingModule_output="";
$formText_ClickHereToOpen_output="";
$formText_ErrorSendingEmail_output="";
$formText_InvalidEmail_output="";
?>