<?php
$preblocks = array (
  'id' => 1,
  'moduleID' => 1,
  'createdBy' => 1,
  'created' => 1,
  'updatedBy' => 1,
  'updated' => 1,
  'sortnr' => 1,
  'content_status' => 1,
  'customerId' => 1,
  'invoiceDate' => 1,
  'dueDate' => 1,
  'totalExTax' => 1,
  'tax' => 1,
  'totalInclTax' => 1,
  'invoiceFile' => 1,
  'showInvoice' => 1,
  'kidNumber' => 1,
  'sentByEmail' => 1,
  'batch_id' => 1,
  'currencyCode' => 1,
  'currencyName' => 1,
  'ownercompany_id' => 1,
  'external_invoice_nr' => 1,
  'creditRefNo' => 1,
  'totalreportId' => 1,
  'ehf_reference' => 1,
  'ehf_invoice_file' => 1,
  'sync_status' => 1,
  'sync_datetime' => 1,
  'sync_confirmed_total_value_without_vat' => 1,
  'sync_confirmed_total_value_with_vat' => 1,
  'sync_error_response' => 1,
  'files_attached' => 1,
);
?>