<?php
$preblocks = array (
  'id' => 1,
  'moduleID' => 1,
  'createdBy' => 1,
  'created' => 1,
  'updatedBy' => 1,
  'updated' => 1,
  'origId' => 1,
  'sortnr' => 1,
  'content_status' => 1,
  'expandArticleMatrix' => 1,
  'activateContactPersonTab' => 1,
  'activateGroupTab' => 1,
  'activate_brreg_sync' => 1,
  'brreg_sync_again_days' => 1,
  0 => 
  array (
    'sys_name' => $formText_CustomerDetailsSection_settingBlocks,
    'sys_childs' => 
    array (
      'activeCustomerBalanceFromAccountingApi' => 1,
      'activateDefaultCreditDays' => 1,
      'defaultCreditDays' => 1,
      'activateDropdownToChooseCompanyOrPrivatePerson' => 1,
      'defaultWhenAddingNewCustomer' => 1,
      'activateChangeCustomerTypeAfterCreated' => 1,
      'activateDisplayCustomerType' => 1,
      'deactivateBrregSearch' => 1,
      'deactivateContactPersonSearch' => 1,
      'deactivateCompanySearch' => 1,
      'hidePersonNumber' => 1,
      'hideBirthdate' => 1,
      'activateCustomerEmailField' => 1,
      'activateHomepageField' => 1,
    ),
    'sys_collapse' => '1',
  ),
  1 => 
  array (
    'sys_name' => $formText_ContactpersonSection_settingBlocks,
    'sys_childs' => 
    array (
      'activateContactPersonAdmin' => 1,
      'activateKeycardsSystem' => 1,
      'activateGateSystem' => 1,
      'contactperson_wifi_access_ftp_address' => 1,
      'contactperson_wifi_access_ftp_port' => 1,
      'contactperson_wifi_access_ftp_username' => 1,
      'contactperson_wifi_access_ftp_password' => 1,
      'activateContactPersonAccess' => 1,
      'activateContactPersonReceiveInfo' => 1,
      'activateContactPersonMessages' => 1,
      'activateContactPersonMainContact' => 1,
      'activateContactPersonDisplayInMemberpage' => 1,
      'activateHideContactPersonInIntranet' => 1,
      'activate_selfdefined_company' => 1,
      'contactperson_mobile_setting' => 1,
      'contactperson_title_setting' => 1,
      'invitation_config' => 1,
      'invitation_accesslevel' => 1,
      'invitation_groupID' => 1,
      'invitation_contentIdField' => 1,
      'invitation_moduleName' => 1,
      'activate_door_access_code' => 1,
      'activateContactPersonExtracheckbox1' => 1,
      'activateContactPersonExtracheckbox2' => 1,
      'activateGroupsInContactperson' => 1,
      'activatePersonalMembership' => 1,
    ),
    'sys_collapse' => '1',
  ),
  2 => 
  array (
    'sys_name' => $formText_GetynetSection_settingBlocks,
    'sys_childs' => 
    array (
      'enable_getynet_connection' => 1,
      'getynet_partner_id' => 1,
      'getynet_partner_pw' => 1,
      'getynet_customer_search' => 1,
      'getynet_show_all_partner_accounts' => 1,
      'getynet_grant_access_for_multi_partner_company' => 1,
      'getynet_grant_admin_access' => 1,
      'getynet_grant_system_admin_access' => 1,
      'getynet_grant_designer_access' => 1,
      'getynet_grant_developer_access' => 1,
      'getynet_new_account_server' => 1,
      'getynet_duplicate_account' => 1,
    ),
    'sys_collapse' => '1',
  ),
  3 => 
  array (
    'sys_name' => $formText_OrdersSection_settingBlocks,
    'sys_childs' => 
    array (
      'activeAccountingProjectOnOrder' => 1,
      'activateAccountingDepartmentOnOrder' => 1,
      'activateFilterProjectByOwnercompany' => 1,
      'connectOrderToProject' => 1,
    ),
    'sys_collapse' => '1',
  ),
  4 => 
  array (
    'sys_name' => $formText_SubscriptionSection_settingBlocks,
    'sys_childs' => 
    array (
      'activateProjectConnection' => 1,
      'project_code_syncing_path' => 1,
      'filterByProjectOnlyConnectedToOwnercompany' => 1,
      'filterByPropertiesOnlyConnectedToOwnercompany' => 1,
      'activateSubscriptionPriceAdjustment' => 1,
      'activateSubscriptionTurnOverBasedRent' => 1,
      'activateSubscriptionGuarantee' => 1,
      'activateSubscriptionOptions' => 1,
      'activateFreeNoBilling' => 1,
      'activateExtraCheckbox' => 1,
      'extraCheckboxName' => 1,
      'activateSubscriptionMarketingContribution' => 1,
      'activateSubscriptionPropertyTaxMustBeCharged' => 1,
      'activateSubscriptionSeparateProvision' => 1,
      'activateSubscriptionBreakCloses' => 1,
      'activateSubscriptionResignation' => 1,
      'activateSubscriptionAdministrationSurchargeNuInPercent' => 1,
      'activate_files_visible_for_performer' => 1,
      'activateAccountingDepartmentOnSubscription' => 1,
      'hide_stopped_subscriptions' => 1,
      'activate_specified_invoicing' => 1,
      'activate_account_connection' => 1,
      'subscription_activate_edit_bookaccount_and_vatcode' => 1,
    ),
    'sys_collapse' => '1',
  ),
  5 => 
  array (
    'sys_name' => $formText_SubscriptionInvoicingAndDate_settingBlocks,
    'sys_childs' => 
    array (
      'hide_subscription_renewal_appeareance_number_of_days_before' => 1,
      'hide_subscription_renewal_appeareance_number_of_days_after' => 1,
      'hide_subscription_renewal_appeareance_month_before_renewaldate' => 1,
      'hide_subscription_renewal_appeareance_month_after_renewaldate' => 1,
      'hide_subscription_renewal_appeareance_same_month_as_renewaldate' => 1,
      'hide_subscription_invoice_date_suggestion_same_as_renewal' => 1,
      'hide_subscription_invoice_date_suggestion_month_before_renewal' => 1,
      'hide_subscription_invoice_date_suggestion_same_month_renewal' => 1,
      'hide_subscription_due_date_from_customer_setting' => 1,
      'hide_subscription_due_date_same_month_as_invoicedate' => 1,
      'hide_subscription_due_date_month_after_invoicedate' => 1,
    ),
    'sys_collapse' => '1',
  ),
  6 => 
  array (
    'sys_name' => $formText_ExpandOrCollapseSections_settingBlocks,
    'sys_childs' => 
    array (
      'collapseCustomerDetails' => 1,
      'collapseContactpersons' => 1,
      'expandFiles' => 1,
      'expandSelfdefinedFields' => 1,
      'expandCleaningWorkers' => 1,
      'expandComments' => 1,
      'expandProjectWithInvoicing' => 1,
      'expandProjectWithInvoicingCanceled' => 1,
      'expandProjectWithInvoicingFinished' => 1,
      'expandProjectWithInvoicingFinishedInvoiced' => 1,
      'expandProjectWithoutInvoicing' => 1,
      'expandProjectWithoutInvoicingCanceled' => 1,
      'expandProjectWithoutInvoicingFinished' => 1,
      'collapseOrders' => 1,
      'expandInvoices' => 1,
      'expandInvoicedOrders' => 1,
      'collapseSubscriptions' => 1,
      'expandProspects' => 1,
      'expandOffers' => 1,
    ),
    'sys_collapse' => '1',
  ),
  7 => 
  array (
    'sys_name' => $formText_ActivateSections_settingBlocks,
    'sys_childs' => 
    array (
      'activateSendEmails' => 1,
      'activateTransactions' => 1,
      'activateProjectsWithInvocing' => 1,
      'activateProjectsWithoutInvocing' => 1,
      'activateProspects' => 1,
      'activateEmails' => 1,
      'activateMessagesSection' => 1,
    ),
    'sys_collapse' => '1',
  ),
  'activateSelfregistered' => 1,
  'linked_insider_account' => 1,
  'linked_insider_account_token' => 1,
  'activateInsiderAccountSyncButton' => 1,
  'activate_intranet_membership' => 1,
  'intranet_membership_object_table' => 1,
  'intranet_membership_objectgroup_table' => 1,
  'activate_sync_customer_hook' => 1,
  'path_sync_customer_hook' => 1,
  'activate_contactperson_overview_page' => 1,
  'activateCompanyImportingForAll' => 1,
  'use_articlename_when_use_articleprice' => 1,
  'activate_customer_export_by_script' => 1,
  'customer_export_by_script_path' => 1,
  'activateSubTypeRenewalChoiceGP' => 1,
  'activateFieldCreditorId' => 1,
  'activateProjects2' => 1,
  'activateSubscriptionOnHold' => 1,
  'activateOfferFrontpage' => 1,
  'activate_incl_tax_in_offer' => 1,
  'activate_member_profile_link' => 1,
  'member_profile_link_url' => 1,
  'member_profile_addextra_member_by_selfdefined' => 1,
  'activate_case_section' => 1,
  'offerDefaultProspectTypeId' => 1,
  'display_customer_accounting_project_number' => 1,
  'accounting_project_number_ownercompany_id' => 1,
  'activate_add_accounting_project_number_when_new_customer' => 1,
  'activate_add_accounting_project_number_on_new_subscription' => 1,
  'activate_add_accounting_project_number_on_new_order' => 1,
  'activate_submember_category' => 1,
  'activate_create_folders_in_files_for_new_customer' => 1,
  'specify_folders_in_files_for_new_customer' => 1,
  'activateMobileField' => 1,
  'activate_subunits' => 1,
  'activate_merge_customer' => 1,
  'activate_shop_name' => 1,
  'activate_customer_responsibleperson' => 1,
  'activate_mark_neworders_for_batchinvoicing' => 1,
  'activate_priceadjustment_department_code_filter' => 1,
  'activate_original_start_date' => 1,
  'activate_contactperson_birthdate' => 1,
  'next_available_projectcode' => 1,
  'deactivate_buttons_for_invoice_date' => 1,
  'activate_contact_type' => 1,
);
?>