<?php
$preblocks = array (
  'id' => 1,
  'moduleID' => 1,
  'createdBy' => 1,
  'created' => 1,
  'updatedBy' => 1,
  'updated' => 1,
  'origId' => 1,
  'sortnr' => 1,
  'content_status' => 1,
  'publicRegisterId' => 1,
  'name' => 1,
  'middlename' => 1,
  'lastname' => 1,
  'birthdate' => 1,
  'personnumber' => 1,
  'notOverwriteByImport' => 1,
  'consideredIrrelevant' => 1,
  'paStreet' => 1,
  'paStreet2' => 1,
  'paPostalNumber' => 1,
  'paCity' => 1,
  'paCountry' => 1,
  'invoiceBy' => 1,
  'invoiceEmail' => 1,
  'phone' => 1,
  'mobile' => 1,
  'homepage' => 1,
  'comments' => 1,
  0 => 
  array (
    'sys_name' => $formText_AdressAndPhone_settingBlocks,
    'sys_childs' => 
    array (
      'vaStreet' => 1,
      'vaStreet2' => 1,
      'vaPostalNumber' => 1,
      'vaCity' => 1,
      'vaCountry' => 1,
      'useOwnInvoiceAdress' => 1,
      'iaStreet1' => 1,
      'iaStreet2' => 1,
      'iaPostalNumber' => 1,
      'iaCity' => 1,
      'iaCountry' => 1,
      'fax' => 1,
      'email' => 1,
    ),
    'sys_collapse' => '1',
  ),
  1 => 
  array (
    'sys_name' => $formText_Info_settingBlocks,
    'sys_childs' => 
    array (
      'numberOfEmplyees' => 1,
      'municipalityName' => 1,
      'companyType' => 1,
      'industries' => 1,
      'industryCode' => 1,
      'industryText' => 1,
      'revenue' => 1,
      'financialYear' => 1,
      'revenueManuallyAdded' => 1,
      'revenueManuallyAddedYear' => 1,
      'publicRegisterContactperson' => 1,
      'publicRegisterContactpFunction' => 1,
    ),
    'sys_collapse' => '1',
  ),
  'creditApproved' => 1,
  'creditLimit' => 1,
  'credittimeDays' => 1,
  'textVisibleInMyProfile' => 1,
  'numberOfUnits' => 1,
  'associationId' => 1,
  'housingcooperativeType' => 1,
  'getynet_customer_id' => 1,
  'create_filearchive_folder' => 1,
  'articlePriceMatrixId' => 1,
  'articleDiscountMatrixId' => 1,
  'overrideAdminFeeDefault' => 1,
  'user_registration' => 1,
  'user_registration_link' => 1,
  'user_registration_token' => 1,
  'user_registration_domain' => 1,
  'customerType' => 1,
  'brreg_compare_date' => 1,
  'brreg_compare_status' => 1,
  'selfregistered' => 1,
  'selfdefined_company_id' => 1,
);
?>