<?php
$preblocks = array (
  'id' => 1,
  'moduleID' => 1,
  'createdBy' => 1,
  'created' => 1,
  'updatedBy' => 1,
  'updated' => 1,
  'sortnr' => 1,
  'content_status' => 1,
  'Status' => 1,
  'projectLeader' => 1,
  'customerID' => 1,
  'contactPerson' => 1,
  'articleNumber' => 1,
  'articleName' => 1,
  'describtion' => 1,
  'amount' => 1,
  'pricePerPiece' => 1,
  'discountPercent' => 1,
  'priceTotal' => 1,
  'currencyId' => 1,
  'projectFAccNumber' => 1,
  'delieveryDate' => 1,
  'expectedTimeuseMinutes' => 1,
  'monthsInvoicedFromStart' => 1,
  'dateFrom' => 1,
  'dateTo' => 1,
  'vatCode' => 1,
  'vatPercent' => 1,
  'bookaccountNr' => 1,
  'gross' => 1,
  'addOnInvoice' => 1,
  'ownercompany_id' => 1,
);
?>