<?php
$formText_KeycardNumber_output="";
$formText_KeycardNumberHex_output="";
$formText_DateFrom_output="";
$formText_DateTill_output="";
$formText_Customer_output="";
$formText_ContactPerson_output="";
$formText_Active_outputKeycard="";
$formText_Showing_Output="";
$formText_Of_output="";
$formText_ShowMore_output="";
$formText_BackToCustomer_Output="";
$formText_All_output="";
$formText_ActiveKeycards_output="";
$formText_KeyCardNumber_output_keycard="";
$formText_Customer_output_keycard="";
$formText_ContactPerson_output_keycard="";
$formText_Search_output="";
?>