<?php
$formText_LastInvoiced_output="";
$formText_Revenue_output="";
$formText_ErrorOccuredPleaseContactSupport_framework="";
$formText_January_output="";
$formText_February_output="";
$formText_March_output="";
$formText_April_output="";
$formText_May_output="";
$formText_June_output="";
$formText_July_output="";
$formText_August_output="";
$formText_September_output="";
$formText_October_output="";
$formText_November_output="";
$formText_December_output="";
$formText_SentDate_output="";
$formText_InvoiceDate_output="";
$formText_Customer_output="";
$formText_SentBy_output="";
$formText_Sum_output="";
$formText_NoDepartment_output="";
$formText_Total_output="";
?>